// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlvjxtdavwndzwedcoun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sdmp4dGRhdnduZHp3ZWRjb3VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MzI4MDEsImV4cCI6MjA1MzQwODgwMX0.wiL2fi2uPtpmZZ9kPIhOHxo2wsTErKW68iEu3xl-J1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);